# Generated by Django 4.1.3 on 2022-11-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('pw_hash', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('credit_balance', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('credits_played', models.PositiveIntegerField(default=0)),
                ('credits_won', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jackpots', to='site_app.user')),
                ('liked_by', models.ManyToManyField(related_name='jackpot_kudos', to='site_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GamesPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_at_start', models.PositiveIntegerField()),
                ('credits_at_end', models.PositiveIntegerField()),
                ('credits_played', models.PositiveIntegerField()),
                ('credits_won', models.PositiveIntegerField()),
                ('_reelstop_blob', models.PositiveIntegerField(db_column='reelstops', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_games_played', to='site_app.user')),
            ],
        ),
    ]
